main/urls.py
from django.urls import path
from . import views
from users.views import redirect_login_view, registration_view, logout_view, login_view


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', login_view, name='login'),
    path('signup/', registration_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('provider/',views.provider_home,name='provider'),
    path('vehicles/',views.vehicles,name='vehicles'),
    path('bookings/',views.bookings,name='bookings'),
    path('book/<int:id>',views.book,name='book'),
    path('add_vehicle/',views.add_vehicle,name='add_vehicle'),
    path('login_required/',redirect_login_view,name='redirect_login'),
    path('removeVehicle/<int:id>',views.remove_vehicle,name='remove_vehicle'),
]

rentalnepal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.


class MyAccountManager(BaseUserManager):

    def create_user(self, username, email,  password=None):
        if not username:
            raise ValueError("User must have username")
        if not email:
            raise ValueError("User must have email")


        user = self.model(
            username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            username=username,
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


ROLE_CHOICES = (
    ('Rider', 'Rider'),
    ('Provider', 'Provider'),
)

class User(AbstractBaseUser):

    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(verbose_name='email', max_length=60, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='Rider')

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    hires_in_progress = models.IntegerField(default=0)
    wallet_balance = models.FloatField(default=0.00)
    amount_owed = models.FloatField(default=0.00)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from main.forms import RegistrationForm, UserAuthenticationForm
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user

@unauthenticated_user
def login_view(request):

    context = {}
    user = request.user
    if user.is_authenticated:
        return redirect('/')

    if request.POST:
        form = UserAuthenticationForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                role = request.user.role
                if role == 'Rider':
                    return redirect('/')
                elif role == 'Provider':
                    return redirect('/provider/')
    else:
        form = UserAuthenticationForm()

    context['login_form'] = form
    return render(request, 'login.html', context)

@unauthenticated_user
def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            role = form.cleaned_data.get('role')
            print(role)
            User = authenticate(username=username, password=raw_password, role=role)
            login(request, User)
            if role=='Rider':
                return redirect('/rider/cars')
            elif role=='Provider':
                return redirect('/provider/')
        else:
            context['registation_form'] = form
    else:
        form = RegistrationForm()
        context['registation_form'] = form

    return render(request, 'signup.html', context)


@unauthenticated_user
def redirect_login_view(request):

    context = {}
    user = request.user
    if user.is_authenticated:
        return redirect('/')

    if request.POST:
        form = UserAuthenticationForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect(request.POST.get('next'))
    else:
        form = UserAuthenticationForm()

    context['login_form'] = form
    context['message'] = "Please log in first"
    return render(request, 'login.html', context)

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

users/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image" style="background-image: url({% static 'img/white-car.jpg' %}); background-position: center; background-size: cover;">
                        </div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    {% if message %}
                                    <h1 class="h4 text-gray-900 mb-4">{{message}}</h1>
                                    
                                    {% else %}
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    {% endif %}
                                </div>
                                <form class="user" method="post">
                                    {% csrf_token %}                         
                                    {{ form.as_p }} 
                                    <input type="hidden" name="next" value="{{ request.GET.next }}" />
                                    <div class="form-group">
                                        <input type="username" class="form-control form-control-user"
                                            name="username"
                                            placeholder="Username" required>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                            name="password" placeholder="Password" required>
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox small">
                                            <input type="checkbox" class="custom-control-input" id="customCheck">
                                            <label class="custom-control-label" for="customCheck">Remember
                                                Me</label>
                                        </div>
                                    </div>
            {% if login_form.non_field_errors %}
                <div style="color:red;">
                    <p>{{ login_form.non_field_errors }}</p>
                </div>
            {% endif %}
                                    <button type="submit" href="index.html" class="btn btn-primary btn-user btn-block">
                                        Login
                                    </button>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'main:signup' %}">Create an Account!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-register-image"  style="background-image: url({% static 'img/ferrari.jpg' %}); background-position: center; background-size: cover;"></div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                        </div>
                        <form class="user" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                    <input type="text" class="form-control form-control-user" name="username"
                                        placeholder="Username">
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control form-control-user" name="email"
                                    placeholder="Email Address">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="password" class="form-control form-control-user"
                                        name="password1" placeholder="Password">
                                </div>
                                <div class="col-sm-6">
                                    <input type="password" class="form-control form-control-user"
                                        name="password2" placeholder="Repeat Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="role" id="role1" value="Rider" checked>
                                    <label class="form-check-label" for="role1">Rider</label>
                                  </div>
                                  <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="role" id="role2" value="Provider">
                                    <label class="form-check-label" for="role2">Provider</label>
                                  </div>
                            </div>
                            <div class="form-group">
                            {% for field in registation_form %}
                        {% for error in field.errors %}
                            <p style="color:red;">{{ error }}</p>
                        {% endfor %}
                        {% if login_form.non_field_errors %}
                            <div style="color:red;">
                                <p>{{ login_form.non_field_errors }}</p>
                            </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                Register Account
                            </button>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="forgot-password.html">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'main:login' %}">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


</body>
</html>