main/urls.py
from django.urls import path
from . import views
from users.views import redirect_login_view, registration_view, logout_view, login_view


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', login_view, name='login'),
    path('signup/', registration_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('provider/',views.provider_home,name='provider'),
    path('vehicles/',views.vehicles,name='vehicles'),
    path('bookings/',views.bookings,name='bookings'),
    path('book/<int:id>',views.book,name='book'),
    path('add_vehicle/',views.add_vehicle,name='add_vehicle'),
    path('login_required/',redirect_login_view,name='redirect_login'),
    path('removeVehicle/<int:id>',views.remove_vehicle,name='remove_vehicle'),
]

rentalnepal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from distutils.command.upload import upload
from enum import auto
from django.db import models
from users.models import User

# Create your models here.

class VehicleImage(models.Model):
    image = models.ImageField(upload_to='vehicles/',null=True)

    def __str__(self):
        return self.image.url

VEHICLE_TYPES = (
        ('Car', 'Car'),
        ('Bike', 'Bike'),
    )


class Vehicle(models.Model):
    name = models.CharField(max_length=150)
    year = models.IntegerField()
    daily_rate = models.IntegerField()
    type = models.CharField(choices=VEHICLE_TYPES,max_length=20)
    images = models.ManyToManyField(VehicleImage,related_name='vehicle_images', blank=True, default=None)
    on_rent = models.BooleanField(default=False)
    provider = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Booking(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle,on_delete=models.CASCADE)
    pickup_time = models.DateTimeField(auto_now=True)
    days = models.IntegerField(default=1)
    payment = models.IntegerField()

    def __str__(self):
        return str(self.pickup_time)

main/forms.py
from random import choices
from secrets import choice
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from users.models import User
from django.contrib.auth import authenticate



class RegistrationForm(UserCreationForm):

    ROLE_CHOICES = (
        ('Rider', 'Rider'),
        ('Provider', 'Provider'),
    )
    email = forms.EmailField(max_length=60, help_text='Add valid email address')
    role = forms.ChoiceField(choices=ROLE_CHOICES,widget=forms.RadioSelect())

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "role"]


class UserAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password')

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Invalid credentials!')

main/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect, render

from .models import  Booking, Vehicle, VehicleImage
from django.contrib.auth.decorators import login_required
from .decorators import provider, rider
from django.contrib import messages

def home(request):
    return render(request, 'index.html')

@login_required
@provider
def provider_home(request):
    vehicles = Vehicle.objects.filter(provider=request.user)
    return render(request,'provider/home.html',{'vehicles':vehicles})

def vehicles(request):
    vehicles = Vehicle.objects.filter(type='Car')[:6]
    if request.method == "POST":
        name = request.POST["query"]
        type = request.POST["type"]
        if name=="":
            vehicles = Vehicle.objects.filter(type=type)[:6]
        else:
            vehicles = Vehicle.objects.filter(name__icontains=name,type=type)[:6]
        if len(vehicles) == 0:
            messages.error(request,"No items found.")
    return render(request,'rider/vehicles.html',{'vehicles':vehicles})

@login_required
@rider
def bookings(request):
    bookings = Booking.objects.filter(user=request.user)
    return render(request,'rider/bookings.html',{'bookings':bookings})

@login_required(login_url='main:redirect_login')
@rider
def book(request,id):
    vehicle = Vehicle.objects.get(id=id)
    if request.method =='POST':
        pickup_date = request.POST.get('pickup_date')
        return_date = request.POST.get('return_date')
        pickup_date = datetime.strptime(pickup_date,'%Y-%m-%d')
        return_date = datetime.strptime(return_date,'%Y-%m-%d')
        # if pickup_date >= return_date or pickup_date<datetime.now():
        #     messages.error(request,'Invalid date.')
        #     return redirect('main:book',id=id)
        days = (return_date - pickup_date).days
        booking = Booking()
        booking.user = request.user
        booking.vehicle = vehicle
        booking.days = days
        booking.payment = vehicle.daily_rate * days
        booking.save()
        return redirect('main:bookings')
    return render(request,'rider/book.html',{'vehicle':vehicle})

@login_required
@provider
def add_vehicle(request):
    if request.method == "POST":
        name = request.POST['name']
        type = request.POST['type']
        daily_rate = request.POST['daily_rate']
        year = request.POST['year']
        provider = request.user
        vehicle = Vehicle(
            name=name,
            type=type,
            daily_rate=daily_rate,
            year=year,
            provider=provider
        )
        vehicle.save()
        if len(request.FILES) != 0:
            for img in request.FILES.getlist('images'):
                image = VehicleImage(image=img)
                image.save()
                vehicle.images.add(image)

        return redirect('main:provider') 
        
    return render(request,'provider/add_vehicle.html')

def remove_vehicle(request,id):
    vehicle = get_object_or_404(Vehicle,id=id)
    if request.user == vehicle.provider:
        vehicle.delete()
        return redirect('main:provider')

main/templates/base.html
{% load static %}
<head>
  <meta charset="utf-8" />
  <title>Rental Nepal</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta content="Free HTML Templates" name="keywords" />
  <meta content="Free HTML Templates" name="description" />

  <!-- Favicon -->
  <link href="img/favicon.ico" rel="icon" />

  <!-- Google Web Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link
    href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap"
    rel="stylesheet"
  />

  <!-- Font Awesome -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css"
    rel="stylesheet"
  />

  <!-- Libraries Stylesheet -->
  <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
  <link
    href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css"
    rel="stylesheet"
  />

  <!-- Customized Bootstrap Stylesheet -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

  <!-- Template Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  
<script src="https://kit.fontawesome.com/f9f03dcea6.js" crossorigin="anonymous"></script>

  {% block head %}
  {% endblock %}
</head>


<body>
  {% include 'navbar.html' %}
  <div class="container">{% block content %} {% endblock content %}</div>
  {% include 'footer.html' %}
</body>

main/templates/car_bike_banner.html
{% load static %}
<!-- Banner Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
      <div class="row mx-0">
        <div class="col-lg-6 px-0">
          <div
            class="px-5 bg-secondary d-flex align-items-center justify-content-between"
            style="height: 350px"
          >
            <img
              class="img-fluid flex-shrink-0 ml-n5 w-50 mr-4"
              src="{% static 'img/banner-left.png' %}"
              alt=""
            />
            <div class="text-right">
              <h3 class="text-uppercase text-light mb-3">Looking for bike?</h3>
              <p class="mb-4">
                Lorem justo sit sit ipsum eos lorem kasd, kasd labore
              </p>
              <a class="btn btn-primary py-2 px-4" href="">Start Now</a>
            </div>
          </div>
        </div>
        <div class="col-lg-6 px-0">
          <div
            class="px-5 bg-dark d-flex align-items-center justify-content-between"
            style="height: 350px"
          >
            <div class="text-left">
              <h3 class="text-uppercase text-light mb-3">Looking for a car?</h3>
              <p class="mb-4">
                Lorem justo sit sit ipsum eos lorem kasd, kasd labore
              </p>
              <a class="btn btn-primary py-2 px-4" href="">Start Now</a>
            </div>
            <img
              class="img-fluid flex-shrink-0 mr-n5 w-50 ml-4"
              src="{% static 'img/banner-right.png' %}"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Banner End -->

main/templates/footer.html
{% load static %}
<!-- Footer Start -->
<div
  class="container-fluid bg-secondary py-5 px-sm-3 px-md-5"
  style="margin-top: 90px"
>
  <div class="row pt-5">
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="text-uppercase text-light mb-4">Contact Us</h4>
      <p class="mb-2">
        <i class="fa fa-map-marker-alt text-white mr-3"></i>123 Street, New
        York, USA
      </p>
      <p class="mb-2">
        <i class="fa fa-phone-alt text-white mr-3"></i>+977 345 67890
      </p>
      <p><i class="fa fa-envelope text-white mr-3"></i>info@rentalnepal.com</p>
      <h6 class="text-uppercase text-white py-2">Follow Us</h6>
      <div class="d-flex justify-content-start">
        <a class="btn btn-lg btn-dark btn-lg-square mr-2" href="#"
          ><i class="fab fa-twitter"></i
        ></a>
        <a class="btn btn-lg btn-dark btn-lg-square mr-2" href="#"
          ><i class="fab fa-facebook-f"></i
        ></a>
        <a class="btn btn-lg btn-dark btn-lg-square mr-2" href="#"
          ><i class="fab fa-linkedin-in"></i
        ></a>
        <a class="btn btn-lg btn-dark btn-lg-square" href="#"
          ><i class="fab fa-instagram"></i
        ></a>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="text-uppercase text-light mb-4">Our Links</h4>
      <div class="d-flex flex-column justify-content-start">
        <a class="text-body mb-2" href="#"
          ><i class="fa fa-angle-right text-white mr-2"></i>Private Policy</a
        >
        <a class="text-body mb-2" href="#"
          ><i class="fa fa-angle-right text-white mr-2"></i>Term & Conditions</a
        >
        <a class="text-body mb-2" href="#"
          ><i class="fa fa-angle-right text-white mr-2"></i>New Member
          Registration</a
        >
        <a class="text-body mb-2" href="#"
          ><i class="fa fa-angle-right text-white mr-2"></i>Affiliate
          Programme</a
        >
        <a class="text-body" href="#"
          ><i class="fa fa-angle-right text-white mr-2"></i>Help & FQAs</a
        >
      </div>
    </div>
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="text-uppercase text-light mb-4">Gallery</h4>
      <div class="row mx-n1">
        <div class="col-4 px-1 mb-2">
          <a href=""><img class="w-100" src="{% static 'img/gallery-1.jpg' %}" alt="" /></a>
        </div>
        <div class="col-4 px-1 mb-2">
          <a href=""><img class="w-100" src="{% static 'img/gallery-2.jpg' %}" alt="" /></a>
        </div>
        <div class="col-4 px-1 mb-2">
          <a href=""><img class="w-100" src="{% static 'img/gallery-3.jpg' %}" alt="" /></a>
        </div>
        <div class="col-4 px-1 mb-2">
          <a href=""><img class="w-100" src="{% static 'img/gallery-4.jpg' %}" alt="" /></a>
        </div>
        <div class="col-4 px-1 mb-2">
          <a href=""><img class="w-100" src="{% static 'img/gallery-5.jpg' %}" alt="" /></a>
        </div>
        <div class="col-4 px-1 mb-2">
          <a href=""><img class="w-100" src="{% static 'img/gallery-6.jpg' %}" alt="" /></a>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 mb-5">
      <h4 class="text-uppercase text-light mb-4"></h4>
      <p class="mb-4"></p>
      <div class="w-100 mb-3">
        <div class="input-group">
          <input
            type="text"
            class="form-control bg-dark border-dark"
            style="padding: 25px"
            placeholder="Your Email"
          />
          <div class="input-group-append">
            <button class="btn btn-primary text-uppercase px-3">Sign Up</button>
          </div>
        </div>
      </div>
      <i> Email </i>
    </div>
  </div>
</div>
<div class="container-fluid bg-dark py-4 px-sm-3 px-md-5">
  <p class="mb-2 text-center text-body">
    &copy; <a href="#">Rental Nepal</a>. All Rights Reserved.
  </p>

  <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
  <p class="m-0 text-center text-body">Designed by Kritartha Kc</p>
</div>
<!-- Footer End -->

main/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- About Start -->
<div class="container-fluid py-5">
  <div class="container pt-5 pb-3">
    <h1 class="display-1 text-primary text-center">01</h1>
    <h1 class="display-4 text-uppercase text-center mb-5">
      Welcome To <span class="text-primary">Rental Nepal</span>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-10 text-center">
        <img class="w-75 mb-4" src="{% static 'img/about.png' %}" alt="" />
        <p>
          Rental app is a web application that makes it easier for the user to
          rent items weather it is brand new or used. This web application
          advertises the product free in cost.
        </p>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-lg-4 mb-2">
        <div
          class="d-flex align-items-center bg-light p-4 mb-4"
          style="height: 150px"
        >
          <div
            class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4"
            style="width: 100px; height: 100px"
          >
            <i class="fa fa-2x fa-headset text-secondary"></i>
          </div>
          <h4 class="text-uppercase m-0">24/7 Rental Support</h4>
        </div>
      </div>
      <div class="col-lg-4 mb-2">
        <div
          class="d-flex align-items-center bg-secondary p-4 mb-4"
          style="height: 150px"
        >
          <div
            class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4"
            style="width: 100px; height: 100px"
          >
            <i class="fa fa-2x fa-car text-secondary"></i>
          </div>
          <h4 class="text-light text-uppercase m-0">Reservation Anytime</h4>
        </div>
      </div>
      <div class="col-lg-4 mb-2">
        <div
          class="d-flex align-items-center bg-light p-4 mb-4"
          style="height: 150px"
        >
          <div
            class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4"
            style="width: 100px; height: 100px"
          >
            <i class="fa fa-2x fa-map-marker-alt text-secondary"></i>
          </div>
          <h4 class="text-uppercase m-0">Lots Of Pickup Locations</h4>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- About End -->

{% include 'car_bike_banner.html' %}

{% endblock %}

main/templates/navbar.html
{% block content %}

<body>
  <!-- Topbar Start -->
  <div class="container-fluid bg-dark py-3 px-lg-5 d-none d-lg-block">
    <div class="row">
      <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
        <div class="d-inline-flex align-items-center">
          <a class="text-body pr-3" href=""><i class="fa fa-phone-alt mr-2"></i>+977 345 6789</a>
          <span class="text-body">|</span>
          <a class="text-body px-3" href=""><i class="fa fa-envelope mr-2"></i>info@rental nepal.com</a>
        </div>
      </div>
      <div class="col-md-6 text-center text-lg-right">
        <div class="d-inline-flex align-items-center">
          <a class="text-body px-3" href="">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a class="text-body px-3" href="">
            <i class="fab fa-twitter"></i>
          </a>
          <a class="text-body px-3" href="">
            <i class="fab fa-linkedin-in"></i>
          </a>
          <a class="text-body px-3" href="">
            <i class="fab fa-instagram"></i>
          </a>
          <a class="text-body pl-3" href="">
            <i class="fab fa-youtube"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- Topbar End -->

  <div class="container-fluid position-relative nav-bar p-0">
    <div class="position-relative px-lg-5" style="z-index: 9">
      <nav class="navbar navbar-expand-lg bg-secondary navbar-dark py-3 py-lg-0 pl-3 pl-lg-5">
        <a href="" class="navbar-brand">
          <h1 class="text-uppercase text-primary mb-1">Rental Nepal</h1>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
          <div class="navbar-nav ml-auto py-0">
            {% with request.resolver_match.url_name as url_name %}
            <a href="{% url 'main:home' %}" class="nav-item nav-link {% if url_name in 'main:home' %}active{% endif %}">Home</a>
            <a href="{% url 'main:vehicles' %}" class="nav-item nav-link {% if url_name in 'main:vehicles' %}active{% endif %}">Vehicles</a>
            {% if user.is_authenticated %}
            <a href="{% url 'main:bookings' %}" class="nav-item nav-link {% if url_name in 'main:bookings' %}active{% endif %}">My Bookings</a>
            <a href="{% url 'main:logout' %}" class="nav-item nav-link">Log Out</a>
            {% else %}
            <a href="" class="nav-item nav-link">About</a>
            <a href="" class="nav-item nav-link">Contact</a>
            <a href="{% url 'main:login' %}" class="nav-item nav-link">Get Started</a>
            {% endif %}
            {% endwith %}
          </div>
        </div>
      </nav>
    </div>
  </div>

  {% endblock %}
</body>